language: ruby
rvm:
- 2.1.0
- 2.0.0
deploy:
  provider: rubygems
  gem: aws-s3crets
  on:
    tags: true
    all_branches: true
  api_key:
    secure: crwL3RJgh7X9hJK3+3gJQ3ucn9uJjJNytEGqgmnVHvAw2WNcg3oHLnro/529wfMc961ZtwMSQ75Zc4jAeDLlxR6AdMTrUJ7SOmvaIkrvmJCUaadu3C8JXY/EoIx/8tJ4V+4u5hkDvcZUoZ9g9kI68r1NtBopJMaSCgrBbYCoCZA=
